name: levelup
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  convex_bottom_bar: ^3.2.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  fonts:
    - family: Lexend
      fonts:
        - asset: fonts/Lexend-Regular.ttf
    - family: Secular
      fonts:
        - asset: fonts/SecularOne-Regular.ttf
  uses-material-design: true
  assets: 
  - assets/gambar/
